2022-06-20 00:22:56,690 INFO    MainThread:2190 [wandb_setup.py:_flush():76] Loading settings from /home/alex/.config/wandb/settings
2022-06-20 00:22:56,690 INFO    MainThread:2190 [wandb_setup.py:_flush():76] Loading settings from /home/alex/detection/ABAW2020TNT-Modified/wandb/settings
2022-06-20 00:22:56,690 INFO    MainThread:2190 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-20 00:22:56,690 INFO    MainThread:2190 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'train.py'}
2022-06-20 00:22:56,690 INFO    MainThread:2190 [wandb_init.py:_log_setup():428] Logging user logs to /home/alex/detection/ABAW2020TNT-Modified/wandb/run-20220620_002256-3tdppuzw/logs/debug.log
2022-06-20 00:22:56,690 INFO    MainThread:2190 [wandb_init.py:_log_setup():429] Logging internal logs to /home/alex/detection/ABAW2020TNT-Modified/wandb/run-20220620_002256-3tdppuzw/logs/debug-internal.log
2022-06-20 00:22:56,691 INFO    MainThread:2190 [wandb_init.py:init():462] calling init triggers
2022-06-20 00:22:56,691 INFO    MainThread:2190 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2022-06-20 00:22:56,691 INFO    MainThread:2190 [wandb_init.py:init():515] starting backend
2022-06-20 00:22:56,691 INFO    MainThread:2190 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-20 00:22:56,700 INFO    MainThread:2190 [backend.py:ensure_launched():217] starting backend process...
2022-06-20 00:22:56,707 INFO    MainThread:2190 [backend.py:ensure_launched():222] started backend process with pid: 2277
2022-06-20 00:22:56,708 INFO    MainThread:2190 [wandb_init.py:init():525] backend started and connected
2022-06-20 00:22:56,711 INFO    MainThread:2190 [wandb_init.py:init():596] updated telemetry
2022-06-20 00:22:56,729 INFO    MainThread:2190 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-06-20 00:22:57,400 INFO    MainThread:2190 [wandb_run.py:_on_init():1924] communicating current version
2022-06-20 00:22:57,537 INFO    MainThread:2190 [wandb_run.py:_on_init():1928] got version response 
2022-06-20 00:22:57,537 INFO    MainThread:2190 [wandb_init.py:init():662] starting run threads in backend
2022-06-20 00:22:57,676 INFO    MainThread:2190 [wandb_run.py:_console_start():1898] atexit reg
2022-06-20 00:22:57,677 INFO    MainThread:2190 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.REDIRECT
2022-06-20 00:22:57,677 INFO    MainThread:2190 [wandb_run.py:_redirect():1776] Redirecting console.
2022-06-20 00:22:57,678 INFO    MainThread:2190 [wandb_run.py:_redirect():1832] Redirects installed.
2022-06-20 00:22:57,679 INFO    MainThread:2190 [wandb_init.py:init():688] run started, returning control to user process
2022-06-20 00:23:04,319 INFO    MainThread:2190 [wandb_watch.py:watch():47] Watching
2022-06-20 01:04:04,213 INFO    MainThread:2190 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 255
2022-06-20 01:04:04,214 INFO    MainThread:2190 [wandb_run.py:_restore():1839] restore
2022-06-20 01:04:05,410 INFO    MainThread:2190 [wandb_run.py:_restore():1839] restore
2022-06-20 01:04:09,288 ERROR   MainThread:2190 [wandb_run.py:_atexit_cleanup():1888] Problem finishing run
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1876, in _atexit_cleanup
    self._on_finish()
  File "/home/alex/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1977, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/home/alex/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1916, in _console_stop
    self._restore()
  File "/home/alex/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1843, in _restore
    self._out_redir.uninstall()
  File "/home/alex/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 740, in uninstall
    self._emulator_write_thread.join(timeout=5)
  File "/usr/lib/python3.8/threading.py", line 1015, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/home/alex/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 642, in handler
    self.handle_window_size_change()
  File "/home/alex/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 673, in handle_window_size_change
    fcntl.ioctl(fd, termios.TIOCSWINSZ, win_size)
OSError: [Errno 9] Bad file descriptor
